---
title: "Лабораторная работа №6"
subtitle: "Разложение чисел на множители"
author:
  - name: Каймакджыоглу Мерич Дорук
    email: 1032245391@pfur.ru
    affiliation:
      - name: Российский университет дружбы народов
        city: Москва
license: "CC BY"
date: 2025-11-02
---

# Информация

## Докладчик

:::::::::::::: {.columns align=center}
::: {.column width="70%"}

* **Каймакджыоглу Мерич Дорук**
* Студент, кафедра Математического моделирования и искусственного интеллекта (ММиИИ)
* Российский университет дружбы народов
* [1032245391@pfur.ru](mailto:1032245391@pfur.ru)
* <https://github.com/dorukme123>

:::
::: {.column width="30%"}
:::
::::::::::::::

# Вводная часть

## Актуальность

-   Задача разложения составных чисел на множители (факторизация) является одной из самых известных задач в теории чисел.
-   Безопасность самой популярной криптосистемы с открытым ключом **RSA** основывается именно на сложности факторизации больших чисел.
-   Если число, используемое в качестве модуля $n$ в RSA, можно разложить на множители $p$ и $q$, система взламывается мгновенно.
-   Изучение таких алгоритмов, как $\rho$-метод Полларда, необходимо для понимания стойкости современных криптографических протоколов.

## Объект и предмет исследования

-   **Объект:** Алгоритмы факторизации целых чисел.
-   **Предмет:** $\rho$-Метод Полларда (Pollard's rho algorithm) для нахождения нетривиальных делителей.

## Цели и задачи

-   **Цель:** Изучить и программно реализовать алгоритм $\rho$-метода Полларда для разложения чисел на множители.
-   **Задачи:**
    -   Изучить теоретические основы метода (парадокс дней рождения, случайные отображения).
    -   Реализовать алгоритм на языке Python.
    -   Реализовать оптимизацию Флойда (алгоритм "черепахи и зайца") для поиска цикла.
    -   Продемонстрировать работу алгоритма на тестовых примерах.

## Материалы и методы

-   **Язык программирования:** Python.
-   **Алгоритм:** $\rho$-метод Полларда.
-   **Математический аппарат:** Модульная арифметика, свойства НОД (GCD), полиномиальные отображения в кольце вычетов.

# Теоретические сведения & Реализация

## Принцип работы $\rho$-метода Полларда

-   **Идея:**
    -   Строится последовательность чисел $x_{i+1} = f(x_i) \pmod n$, где $f(x)$ — полином (обычно $x^2 + c$).
    -   Так как количество вычетов по модулю $n$ конечно, последовательность обязательно зациклится.
    -   Граф этой последовательности напоминает греческую букву $\rho$ (ро).

-   **Поиск коллизии:**
    -   Мы ищем два индекса $i \neq j$ таких, что $x_i \equiv x_j \pmod p$, где $p$ — делитель $n$.
    -   Это проверяется вычислением $d = НОД(|x_i - x_j|, n)$.
    -   Если $1 < d < n$, то $d$ — искомый делитель.

## Демонстрация

1. Основной алгоритм
```python
import math
def f(x, n, constant):
    return (x**2 + constant) % n

def pollard_rho(n, c_start=1, constant=1):
    a = c_start
    b = c_start
    d = 1
    i = 0

    print(f"\n{"i":<5} {"a":<15} {"b":<15} {"GCD(a-b, n)":<15}")
    print("-"*55)

    while d == 1:
        i += 1

        a = f(a, n, constant)
        b = f(f(a, n, constant), n, constant)
        d = math.gcd(abs(a - b), n)
        print(f"{i:<5} {a:<15} {b:<15} {d:<15}")

        if d == n:
            return None
        elif 1 < d < n:
            return d
    return d

if __name__ == "__main__":
    target_n = 1359331
    start_c = 1
    func_constant = 5

    factor = pollard_rho(target_n, c_start=start_c, constant=func_constant)

    if factor:
        other_factor = target_n // factor
        print(f"Verify: {factor} * {other_factor} = {target_n}")
```

## Выводы

- В ходе лабораторной работы был успешно реализован ρ-метод Полларда.
- На практике подтверждена эффективность метода для поиска делителей составных чисел.
- Метод работает значительно быстрее простого перебора делителей.
- Реализация алгоритма Флойда (черепаха и заяц) позволила эффективно находить цикл в последовательности и вычислять GCD для нахождения делителя.
- Работа закрепляет понимание математических основ криптоанализа алгоритма RSA.