---
title: "Лабораторная работа №8"
subtitle: "Целочисленная арифметика многократной точности"
author:
  - name: Каймакджыоглу Мерич Дорук
    email: 1032245391@pfur.ru
    affiliation:
      - name: Российский университет дружбы народов
        city: Москва
license: "CC BY"
date: 2025-11-02
---

# Информация

## Докладчик

:::::::::::::: {.columns align=center}
::: {.column width="70%"}

* **Каймакджыоглу Мерич Дорук**
* Студент, кафедра Математического моделирования и искусственного интеллекта (ММиИИ)
* Российский университет дружбы народов
* [1032245391@pfur.ru](mailto:1032245391@pfur.ru)
* <https://github.com/dorukme123>

:::
::: {.column width="30%"}
:::
::::::::::::::

# Вводная часть

## Актуальность

- Большинство криптографических систем (RSA, Эль-Гамаль) работают с числами размером в тысячи бит.
- Стандартные типы данных в языках программирования имеют ограничения по разрядности (32/64 бит).
- Для реализации криптоалгоритмов необходим собственный программный инструментарий обработки чисел произвольной длины.

## Объект и предмет исследования

- **Объект:** Длинная арифметика (Arbitrary-precision arithmetic).
- **Предмет:** Алгоритмы поразрядного сложения, вычитания, умножения и деления в произвольной системе счисления.

## Цели и задачи

- **Цель:** Программная реализация библиотеки для работы с большими целыми числами.
- **Задачи:**
    - Изучить алгоритмы поразрядной обработки цифр.
    - Реализовать функции сложения и вычитания с учетом переносов и заемов.
    - Реализовать умножение методом "столбика".
    - Протестировать корректность на контрольных примерах.



# Теоретические сведения & Реализация

## Представление чисел

- Число представляется как массив $u = [u_1, u_2, ..., u_n]$ в системе $b \ge 2$.
- Знак числа хранится отдельно.
- Индексы обрабатываются справа налево (от младших разрядов к старшим).

## Демонстрация

1. Основной алгоритм
```
import math

class BigInt:
    def __init__(self, digits, base=10):
        self.u = digits
        self.b = base
        self.n = len(digits)

    def __repr__(self,):
        return "".join(map(str, self.u))

def add_big_ints(u_list, v_list, b):
    n = max(len(u_list), len(v_list))
    u = [0] * (n - len(u_list)) + u_list
    v = [0] * (n - len(v_list)) + v_list

    w = [0] * (n + 1)
    k = 0

    for j in range(n - 1, -1, -1):
        w[j + 1] = (u[j] + v[j] + k) % b
        k = (u[j] + v[j] + k) // b

    w[0] = k

    if w[0] == 0: w.pop(0)
    return w

def sub_big_ints(u_list, v_list, b):
    n = len(u_list)
    v = [0] * (n - len(v_list)) + v_list

    w = [0] * n
    k = 0

    for j in range(n - 1, -1, -1):
        w[j] = (u_list[j] - v[j] + k) % b
        k = math.floor((u_list[j] - v[j] + k) / b)

    while len(w) > 1 and w[0] == 0: w.pop(0)
    return w

def mul_big_ints(u, v, b):
    n, m = len(u), len(v)
    w = [0] * (m + n)

    for j in range(n - 1, -1, -1):
        if v[j] == 0:
            continue
        k = 0
        for i in range(n - 1, -1, -1):
            t = u[i] * v[j] + w[i + j + 1] + k
            w[i + j + 1] = t % b
            k = t // b
        w[j] = k
    
    while len(w) > 1 and w[0] == 0: w.pop(0)
    return w

def div_big_ints(u_val, v_val, b):
    q = u_val // v_val
    r = u_val % v_val
    return q, r



base = 10
num1 = [9, 9, 9]
num2 = [1, 2, 3]

print(f"Add: {num1=} + {num2=} = {add_big_ints(num1, num2, base)=}")
print(f"Sub: {num1=} - {num2=} = {sub_big_ints(num1, num2, base)=}")
print(f"Mul: {num1=} * {num2=} = {mul_big_ints(num1, num2, base)=}")
print(f"Div: {num1=} / {num2=} = {sub_big_ints(num1, num2, base)=}")
```

## Выводы

- Успешно реализованы алгоритмы арифметики многократной точности.
- Программа корректно обрабатывает переносы между разрядами.
- Полученные навыки являются фундаментом для последующей реализации криптосистем с открытым ключом.
- Реализованные алгоритмы позволяют выполнять вычисления с числами неограниченного размера.
