---
## Author
author:
  name: Каймакджыоглу Мерич Дорук
  email: 1032245391@pfur.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Отчёт по лабораторной работе №6"
subtitle: "Разложение чисел на множители"
license: "CC BY"
---

# Цель работы

Целью данной лабораторной работы является изучение и практическая реализация алгоритмов разложения составных чисел на множители.
Особое внимание уделяется $\rho$-методу Полларда (Pollard's rho algorithm).
Понимание и реализация этих алгоритмов имеет критическое значение, поскольку задача факторизации лежит в основе безопасности многих криптосистем с открытым ключом, в частности RSA. Если число можно быстро разложить на множители, криптосистема становится уязвимой.

# Задание

Реализовать программно рассмотренный алгоритм:
- Алгоритм, реализующий $\rho$-метод Полларда для факторизации чисел.
- Создать главный скрипт, который импортирует этот алгоритм и демонстрирует его работу на примере из методических указаний и других чисел.

# Теоретическое введение

Задача разложения составного числа на множители (факторизация) формулируется следующим образом: для данного положительного целого числа $n$ найти его представление в виде произведения простых чисел $n=p_{1}^{\alpha_{1}}p_{2}^{\alpha_{2}}...p_{s}^{\alpha_{s}}$.
На практике для криптографии часто достаточно найти разбиение числа на два нетривиальных сомножителя $n=pq$, где $1 < p \le q < n$.

Существует множество алгоритмов факторизации. Одним из эффективных вероятностных методов является **$\rho$-метод Полларда**.
Он предложил использовать случайное отображение $f: S \rightarrow S$ со сжимающими свойствами, например, полином $f(x) = (x^2 + c) \pmod n$.

Алгоритм строит последовательность $x_{i+1} = f(x_i) \pmod n$. Из-за конечности множества вычетов по модулю $n$ эта последовательность рано или поздно зациклится (форма буквы $\rho$).
Для поиска делителя вычисляется $d = НОД(|x_i - x_j|, n)$. Если $1 < d < n$, то $d$ является искомым делителем.
Для оптимизации поиска цикла часто используется метод "черепахи и зайца" (алгоритм Флойда), где сравниваются $x_i$ и $x_{2i}$. Сложность алгоритма оценивается как $O(\sqrt{p})$, где $p$ — наименьший делитель числа $n$.

# Выполнение лабораторной работы

Для выполнения задания был разработан скрипт на языке Python, реализующий метод Полларда.

1. Реализация алгоритма Полларда
```python
import math
def f(x, n, constant):
    return (x**2 + constant) % n

def pollard_rho(n, c_start=1, constant=1):
    a = c_start
    b = c_start
    d = 1
    i = 0

    print(f"\n{"i":<5} {"a":<15} {"b":<15} {"GCD(a-b, n)":<15}")
    print("-"*55)

    while d == 1:
        i += 1

        a = f(a, n, constant)
        b = f(f(a, n, constant), n, constant)
        d = math.gcd(abs(a - b), n)
        print(f"{i:<5} {a:<15} {b:<15} {d:<15}")

        if d == n:
            return None
        elif 1 < d < n:
            return d
    return d

if __name__ == "__main__":
    target_n = 1359331
    start_c = 1
    func_constant = 5

    factor = pollard_rho(target_n, c_start=start_c, constant=func_constant)

    if factor:
        other_factor = target_n // factor
        print(f"Verify: {factor} * {other_factor} = {target_n}")
```

## Результаты выполнения

Тест 1: Факторизация числа n = 1359331
Параметры: начальное значение = 1, константа c = 5
Результат: Найден делитель 1181
Проверка: 1181 * 1151 = 1359331

# Выводы

В ходе выполнения данной лабораторной работы был успешно реализован вероятностный алгоритм разложения чисел на множители — ρ-метод Полларда. Программа корректно нашла нетривиальный делитель для контрольного примера из методических материалов (1359331=1181⋅1151), а также успешно справилась с факторизацией других составных чисел. Было подтверждено на практике, что алгоритм позволяет находить делители числа значительно быстрее, чем метод полного перебора (пробного деления), особенно если наименьший делитель числа не слишком велик по сравнению с n​. Эта работа позволила углубить понимание математических основ криптоанализа, так как стойкость алгоритма RSA напрямую зависит от сложности задачи факторизации, которую мы решали.

# Список литературы{.unnumbered}

::: {#Методические указания к лабораторной работе №6}
:::
